// import Header from '../Header';
// import Side from '../Side';
import Image from "next/image";
import Head from "next/head";
import styles from "./layout.module.css";
import { NextPage } from "next";
import { ReactNode } from "react";

interface Props {
  title: string;
  children: ReactNode;
}

const Layout: NextPage<Props> = ({ title, children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>{children}</main>
      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
export default Layout;
